INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Boop 'N' Bop", "funtimes", 10000, "2018-02-15", "2019-01-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Food for the Homeless", "charity", 20000, "2018-02-01", "2018-12-24");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Destroy All the McDonald's", "charity", 2000000, "2018-02-01", "2020-04-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Exile Donald Trump to Mars", "charity", 2500000, "2018-03-01", "2020-03-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Make LEGOs Great Again", "fun charity", 1000000, "2018-02-05", "2019-12-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Eat Moar Plants", "activism", 500000, "2018-02-14", "2020-09-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Send Cats to Mars Colonists", "community service", 3000000, "2018-02-06", "2030-06-30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Roads for Boston", "community service", 4000000, "2018-02-01", "2040-12-25");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Better Our Publich Schools", "community development", 2000000, "2018-04-21", "2020-09-01");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Replace Dunkin Donuts with Peet's Coffee", "community development", 5000000, "2018-05-05", "2027-07-04");

INSERT INTO users (name, age) VALUES ("John", 35);
INSERT INTO users (name, age) VALUES ("Jacob", 41);
INSERT INTO users (name, age) VALUES ("Jingleheimer", 83);
INSERT INTO users (name, age) VALUES ("Schmitty", 11);
INSERT INTO users (name, age) VALUES ("Patricia", 28);
INSERT INTO users (name, age) VALUES ("Don", 49);
INSERT INTO users (name, age) VALUES ("Pat", 21);
INSERT INTO users (name, age) VALUES ("Melissa", 32);
INSERT INTO users (name, age) VALUES ("Earl", 97);
INSERT INTO users (name, age) VALUES ("St. Belvedere", 112);
INSERT INTO users (name, age) VALUES ("Andy", 26);
INSERT INTO users (name, age) VALUES ("Jesus", 1);
INSERT INTO users (name, age) VALUES ("Voldemort", 125);
INSERT INTO users (name, age) VALUES ("Martha", 53);
INSERT INTO users (name, age) VALUES ("Judy", 34);
INSERT INTO users (name, age) VALUES ("Northwest", 15);
INSERT INTO users (name, age) VALUES ("Mike", 23);
INSERT INTO users (name, age) VALUES ("Marie", 39);
INSERT INTO users (name, age) VALUES ("Ethel", 91);
INSERT INTO users (name, age) VALUES ("Chuck", 22);
INSERT INTO users (name, age) VALUES ("Stardust", 17);
INSERT INTO users (name, age) VALUES ("Kirito", 18);
INSERT INTO users (name, age) VALUES ("Paige", 16);
INSERT INTO users (name, age) VALUES ("Bob", 61);
INSERT INTO users (name, age) VALUES ("Billy Joe", 43);
INSERT INTO users (name, age) VALUES ("Mikhail", 63);
INSERT INTO users (name, age) VALUES ("Ryan", 40);
INSERT INTO users (name, age) VALUES ("Nicholas", 48);
INSERT INTO users (name, age) VALUES ("Vanessa", 19);
INSERT INTO users (name, age) VALUES ("Mary", 23);
INSERT INTO users (name, age) VALUES ("Christa", 25);

-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
-- INSERT INTO pledges (amount, user_id, project_id) VALUES ();
